# Generated by Django 2.2 on 2019-05-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingminutes',
            old_name='meetingid',
            new_name='meeting_id',
        ),
        migrations.AddField(
            model_name='meetings',
            name='meetingAgenda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
