# Generated by Django 2.2 on 2019-05-28 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0002_auto_20190527_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetings',
            options={'verbose_name_plural': 'Meetings'},
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='meeting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubapp.Meetings'),
        ),
    ]
