# Generated by Django 2.2 on 2019-05-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0003_auto_20190528_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminutes',
            name='meeting_id',
            field=models.CharField(max_length=255),
        ),
    ]
