# Generated by Django 2.2 on 2019-05-28 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubapp', '0004_auto_20190528_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='meetingminutes',
            name='attendance',
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='attendance',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='meeting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clubapp.Meetings'),
        ),
    ]
