# Generated by Django 2.2 on 2019-05-31 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0005_auto_20190528_0226'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resource',
            table='resource',
        ),
    ]
